### ISSUE TITLE
It appears that you may need to fix a Relative Path Environment Variable

### ISSUE THREAD

**Issue by KirkH420** [daemondevin/DiscordPortable#7]
Hello, 
I was very excited to have stumbled upon this project, unfortunately it fails to launch after the PAL installer completes unpacking the program. It throws an exception immediately "Error: A JavaScript error occurred in the main process" and it goes on to say, "Cannot find module C:\Users\devin\AppData\Roaming\BetterDiscord\data\betterdiscord.asar"

Clearly, my computer should not be trying to find files that are stored on YOUR machine. I've included a screenshot showing the error message. At the moment I cannot think of anything else that I could provide to help you find the problem. I do hope that you find this report helpful.

![Screenshot 2022-07-18 080018](https://user-images.githubusercontent.com/29521840/179517732-40c8e3ab-6ec2-404d-9325-17893572ca85.png)

**Comment by daemondevin** [comment]
Well that's embarrassing. I meant to incorporate BetterDiscord as a plugin to Discord Portable but forgot to write the code for it.  I'll work that out right now. Lol.

**Comment by daemondevin** [comment]
Try [Revision 2](https://github.com/daemondevin/DiscordPortable/releases/tag/v1.0.9005-Rev2) and see if that fixed it..

**Comment by KirkH420** [comment]
Well I'm sure you already know this by now, but yes this did fix the issue. Sorry it took almost a year to answer your comment. I do try to keep up with bug reports that I make but I guess I let this one slip. Anyway, thanks a lot for your efforts!
