### ISSUE TITLE
Not usable on surface 2 with windows 10

### ISSUE THREAD

**Issue by VarNasadra** [daemondevin/DiscordPortable#9]
so i have a windows surface 2 (2014 model) with a version of windows 10 enterprise downloaded onto it and ive tried eveything to get portable to download but i keep getting the pop up saying in order to download apps i need to use the microsoft store but it doesnt exist on the microsoft store, any advice or way to help? the only thing i havent tried is to try to download the microsoft store version onto a usb then transfer it over or try to trick the store into having the app

**Comment by daemondevin** [comment]
Try disabling Windows S mode. I believe that's the problem. Once disabled, it won't ask you to use the Microsoft store to download the program anymore. Let me know if that worked.
